### PR TITLE
Fix Script Not Found

### PR DESCRIPTION
**Pull request by itotallyrock**

### CODE REVIEW

**Comment by SEAPUNK** [comment]
Thanks, but this was an issue with my server -- the file is there, the HTTPS cert was simply invalid.

Fixed.

**Comment by SEAPUNK** [comment]
...on second thought, it would probably be better if the FileSaver resource was provided from a dedicated CDN.

Could you update the PR to use the following URL?

https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2014-11-29/FileSaver.min.js

**Comment by SEAPUNK** [comment]
Does the userscript work with this FileSaver.js file? As soon as you can confirm the userscript still works, I will merge it.

**Comment by itotallyrock** [comment]
I changed it in my user script and edited the file again with the CDN instead of a gist.
I didn't go through and check the file to see if you were using a custom version so I just used the source provided in the script and uploaded it to gist before.  But this is definitely better and more long term.

**Comment by SEAPUNK** [comment]
Alright, sweet. Thanks!

**Comment by SEAPUNK** [comment]
Pushed the new Userscript version to http://pye.sq10.net  - http://pye.sq10.net/s/userscript/pye.user.js

**Pull request merged**
